remote_theme: rundocs/jekyll-rtd-theme

title: Linguagem Potigol
description: Documentação da Linguagem Potigol

meta:
  versao: 1.0.0-RC1

readme_index:
  with_frontmatter: true

translate:
  # shortcodes
  danger: perigo
  #note:
  tip: dica
  warning: atenção
  # 404
  #not_found:
  # copyright
  revision: versão
  # search
  #searching:
  #search:
  search_docs: pesquisar documentação
  #search_results:
  #search_results_found: # the "#" in this translate will replaced with results size!
  #search_results_not_found:
